# Generated by Django 2.2.5 on 2019-09-29 20:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Einsatz',
            fields=[
                ('Erstellt', models.DateTimeField(auto_now_add=True)),
                ('Nummer', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('Adresse', models.CharField(max_length=200)),
                ('Ende', models.DateTimeField(default=None, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ort',
            fields=[
                ('PLZ', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)])),
                ('Kurzname', models.CharField(max_length=3)),
                ('Langname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Stichwort',
            fields=[
                ('Kurzname', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('Langname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Meldung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Inhalt', models.TextField()),
                ('Wichtig', models.BooleanField(default=False)),
                ('Erstellt', models.DateTimeField(auto_now_add=True)),
                ('Autor', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('Einsatz', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='doku.Einsatz')),
            ],
        ),
        migrations.CreateModel(
            name='Fahrzeuge',
            fields=[
                ('Funkname', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('Typ', models.CharField(max_length=10)),
                ('Ort', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doku.Ort')),
            ],
        ),
        migrations.CreateModel(
            name='Fahrzeug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Zugfuehrer', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('Gruppenfuehrer', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('Mannschaft', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('Atemschutz', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('Autor', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('Einsatz', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='doku.Einsatz')),
                ('Name', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='doku.Fahrzeuge')),
            ],
        ),
        migrations.AddField(
            model_name='einsatz',
            name='Ort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doku.Ort'),
        ),
        migrations.AddField(
            model_name='einsatz',
            name='Stichwort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doku.Stichwort'),
        ),
    ]
