# Generated by Django 2.2.5 on 2019-09-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doku', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stichwort',
            name='Langname',
            field=models.CharField(max_length=50),
        ),
    ]
