# Generated by Django 2.2.5 on 2019-10-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doku', '0002_auto_20190930_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='einsatz',
            name='Nummer',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
