# Generated by Django 6.1 on 2026-08-24 15:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doku', '0002_alter_meldung_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EinsatzRevision',
            fields=[
                ('Einsatz', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Revision', serialize=False, to='doku.einsatz')),
                ('Version', models.BigIntegerField(default=0, editable=False)),
                ('Geaendert', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Lagekarte',
        ),
    ]

