# Generated by Django 2.2.5 on 2019-10-07 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doku', '0003_auto_20191001_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nachname', models.CharField(editable=False, max_length=50)),
                ('Vorname', models.CharField(editable=False, max_length=50)),
                ('Rolle', models.CharField(editable=False, max_length=50)),
                ('Notizen', models.CharField(max_length=200)),
                ('Einsatz', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='doku.Einsatz')),
            ],
        ),
    ]
