# Generated by Django 2.2.6 on 2019-10-19 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doku', '0004_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='einsatz',
            name='extNummer',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Lagekarte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nummer', models.IntegerField(editable=False)),
                ('Name', models.CharField(max_length=200)),
                ('image', models.TextField()),
                ('canvas_image', models.TextField()),
                ('Einsatz', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='doku.Einsatz')),
            ],
        ),
    ]
