# Generated by Django 2.2.6 on 2019-11-05 16:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doku', '0006_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lagekarte',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='lagekarte',
            name='Nummer',
        ),
        migrations.RemoveField(
            model_name='lagekarte',
            name='canvas_image',
        ),
        migrations.RemoveField(
            model_name='lagekarte',
            name='image',
        ),
        migrations.AddField(
            model_name='lagekarte',
            name='Bild',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='lagekarte',
            name='Erstellt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lagekarte',
            name='Temp',
            field=models.BooleanField(default=False),
        ),
    ]
