# Generated by Django 2.2.6 on 2019-11-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doku', '0007_auto_20191105_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Einstellungen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='Einsatzverwaltung', max_length=50)),
                ('Schulung', models.BooleanField(default=False)),
                ('Lagekarten', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
