# Generated by Django 2.2.6 on 2019-11-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doku', '0008_einstellungen'),
    ]

    operations = [
        migrations.AddField(
            model_name='einsatz',
            name='OrtFrei',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
