# Generated by Django 2.2.6 on 2019-11-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doku', '0009_einsatz_ortfrei'),
    ]

    operations = [
        migrations.AddField(
            model_name='einsatz',
            name='Einsatzleiter',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
