# Generated by Django 2.2.6 on 2019-12-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doku', '0012_auto_20191219_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='fahrzeuge',
            name='Zug',
            field=models.ManyToManyField(to='doku.Zug'),
        ),
    ]
