# Generated by Django 2.2.6 on 2019-12-20 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doku', '0013_auto_20191220_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fahrzeuge',
            name='Zug',
        ),
        migrations.AddField(
            model_name='fahrzeuge',
            name='Zug',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='doku.Zug'),
        ),
    ]
