# Generated by Django 2.2.6 on 2019-12-20 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doku', '0014_auto_20191220_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fahrzeuge',
            name='Zug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doku.Zug'),
        ),
    ]
