# Generated by Django 3.0.1 on 2019-12-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doku', '0015_auto_20191220_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='einsatz',
            name='Training',
            field=models.BooleanField(default=False),
        ),
    ]
