# Generated by Django 3.0.1 on 2019-12-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doku', '0016_einsatz_training'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='einstellungen',
            name='Schulung',
        ),
        migrations.AddField(
            model_name='einstellungen',
            name='Einsatzleiter',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='einstellungen',
            name='Einsatznummer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='einstellungen',
            name='Fahrzeuge',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='einstellungen',
            name='Personen',
            field=models.BooleanField(default=True),
        ),
    ]
