# Generated by Django 3.0.1 on 2020-05-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doku', '0017_auto_20191229_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='zug',
            name='Farbe',
            field=models.CharField(default='#bbbbbb', max_length=7),
        ),
    ]
