# Generated by Django 3.0.1 on 2020-05-23 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doku', '0018_zug_farbe'),
    ]

    operations = [
        migrations.AddField(
            model_name='meldung',
            name='Zug',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doku.Zug'),
        ),
    ]
