# Generated by Django 3.0.1 on 2020-05-31 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doku', '0019_meldung_zug'),
    ]

    operations = [
        migrations.AddField(
            model_name='einstellungen',
            name='Hydranten',
            field=models.CharField(default='http://openfiremap.org/', max_length=1000),
        ),
    ]
